import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import AuthProvider from "@/contexts/AuthProvider";
import Header from "@/components/header/Header";
import { QuizProvider } from "@/contexts/QuizContext";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "A Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <UserProvider>
          <QuizProvider>
            <body className={manrope.className}>
              <Header />
              <main>{children}</main>
            </body>
          </QuizProvider>
        </UserProvider>
      </AuthProvider>
    </html>
  );
}
